---

- name: Download jemalloc release
  unarchive:
    src: "{{ jemalloc_repo }}/releases/download/{{ jemalloc_version }}/jemalloc-{{ jemalloc_version }}.tar.bz2"
    dest: '/tmp'
    remote_src: true
    mode: 'u=rwx,g=rx,o='
    creates: "/tmp/jemalloc-{{ jemalloc_version }}"

- name: Configure build for jemalloc
  command: './configure'
  args:
    chdir: "/tmp/jemalloc-{{ jemalloc_version }}"

- name: Build the default target for jemalloc
  make:
    chdir: "/tmp/jemalloc-{{ jemalloc_version }}"

- name: Build the `install` target for jemalloc
  make:
    chdir: "/tmp/jemalloc-{{ jemalloc_version }}"
    target: install

- name: Remove obsolete files
  file:
    path: "/tmp/jemalloc-{{ jemalloc_version }}"
    state: absent
